# Generated by .github/workflows/release.yml for v1.1.2. Do not edit:
# change packaging/homebrew/tervin-formula.rb, which this is built from.
# A Homebrew *formula* that builds Tervin from source.
#
# Exists alongside the cask because the two differ in a way that matters on macOS: a
# cask downloads a prebuilt app and Homebrew marks it quarantined, so an unsigned build
# hits Gatekeeper. A formula compiles locally, and a locally produced binary is never
# quarantined — so this route works with no Apple Developer ID and no warning dialog.
#
# The cost is real: a Rust and Node toolchain, and several minutes of compilation. Both
# routes are offered because neither is right for everyone.
class Tervin < Formula
  desc "Agent-native terminal workspace"
  homepage "https://github.com/QuintinBotes/tervin"
  url "https://github.com/QuintinBotes/tervin/archive/refs/tags/v1.1.2.tar.gz"
  sha256 "a2457311e25a84e989b80fa2b389b07192358dbb8e6614b187d5511efc988b38"
  license "MIT"
  head "https://github.com/QuintinBotes/tervin.git", branch: "main"

  # `pnpm` does not imply `node`: Homebrew's pnpm formula declares no dependency on it and
  # says so in its own caveats, so both are named or the build gets a package manager and no
  # runtime for Vite or the Tauri CLI. Which pnpm Homebrew ships does not have to match the
  # one this repository pins — pnpm reads `packageManager` from package.json, installs that
  # exact version under its own home and re-executes.
  depends_on "node" => :build
  depends_on "pnpm" => :build
  depends_on "rust" => :build
  depends_on :macos

  def install
    # `pnpm`, because the tarball above is the tagged tree and that tree ships
    # `pnpm-lock.yaml` and neither `package-lock.json` nor `npm-shrinkwrap.json`. `npm ci`
    # installs only from one of those two and exits EUSAGE when it finds neither, which is
    # what both copies of this formula did for the whole of v0.1.0 — so this route has never
    # built. `npm install` is not the repair either: it would ignore the lockfile it cannot
    # read and write a second one beside it. `--frozen-lockfile` is the half that matters
    # after the manager, because a resolution disagreeing with the lockfile then stops the
    # build instead of quietly installing something else.
    #
    # No `--store-dir`: Homebrew points `HOME` at `<buildpath>/.brew_home` for the whole
    # staged build, so pnpm's store and its own home are already inside the one directory the
    # sandbox allows writes to, and a flag here would only pin them somewhere else.
    system "pnpm", "install", "--frozen-lockfile"
    system "pnpm", "exec", "tauri", "build", "--bundles", "app"

    # The bundle stays in the prefix and nowhere else. Homebrew links a formula's
    # binaries, never its app bundles, so nothing appears in /Applications — observed on
    # the 2026-08-19 run, which found none. The shim reaches the bundle by its keg path.
    prefix.install "target/release/bundle/macos/Tervin.app"

    # The manual and the completion scripts come out of the binary that was just built —
    # `tervin man` and `tervin completions <shell>` print and exit before any window
    # exists — so what this installs can never describe a different build than the one
    # beside it. Guarded on the source file that implements those words rather than on a
    # version compare: a build of a tag that predates them (v0.1.0) opens the workspace
    # when handed a word it does not know, and a window in this sandbox is a hang, not
    # an error. The file existing in the tree that just compiled is the evidence the
    # words exist in the binary.
    if (buildpath/"crates/tervin-app/src/cli.rs").exist?
      tervin = prefix/"Tervin.app/Contents/MacOS/tervin"
      (man1/"tervin.1").write Utils.safe_popen_read(tervin.to_s, "man")
      (zsh_completion/"_tervin").write Utils.safe_popen_read(tervin.to_s, "completions", "zsh")
      (bash_completion/"tervin").write Utils.safe_popen_read(tervin.to_s, "completions", "bash")
      (fish_completion/"tervin.fish").write Utils.safe_popen_read(tervin.to_s, "completions", "fish")
    end

    # A CLI shim, and this is the only route that installs one — so it has to reach both
    # halves of the binary rather than only the window.
    #
    # `tervin daemon start|status|stop` is answered in `main` before any window exists, and
    # `open` cannot carry it: it returns as soon as LaunchServices has started the process,
    # so the subcommand's output and its exit status arrive nowhere the caller can read
    # them. `tervin daemon status` through such a shim prints nothing and succeeds, which is
    # the worst of the three possible answers. Those words exec the inner executable.
    #
    # Everything else still goes through `open`, because a bundle launched that way gets its
    # Info.plist, its icon and a normal application lifecycle, and the inner Mach-O run
    # straight leaves the web view without them.
    #
    # `daemon`, `man` and `completions` are the whole CLI surface: the three first words
    # `main` answers before any window exists, each declared in the one table in
    # crates/tervin-app/src/cli.rs that also renders tervin(1) and the completion
    # scripts. This case list is necessarily a copy of that table's first words — a shim
    # cannot ask the binary which words it owns without running it — so the repository's
    # docs-consistency suite drives this heredoc with each of the three and fails the
    # copy that falls behind.
    (bin/"tervin").write <<~SH
      #!/bin/sh
      case "${1:-}" in
        daemon|man|completions) exec "#{prefix}/Tervin.app/Contents/MacOS/tervin" "$@" ;;
        *) exec open -a "#{prefix}/Tervin.app" --args "$@" ;;
      esac
    SH
    chmod 0755, bin/"tervin"
  end

  def caveats
    <<~EOS
      Built from source, so macOS does not quarantine it and there is no Gatekeeper
      warning.

      Tervin injects its shell integration per pane and never modifies your rc files.
      Disable it with TERVIN_SHELL_INTEGRATION=0 or in Settings.

      Tervin is a terminal, not a sandbox. Agents run with your privileges. See
      SECURITY.md for what its permission gates can and cannot enforce.
    EOS
  end

  test do
    # The app cannot be launched headlessly, so this asserts the bundle is well formed
    # and that its executable is the one the shim points at.
    assert_predicate prefix/"Tervin.app/Contents/MacOS/tervin", :executable?
    assert_match "Tervin.app", (bin/"tervin").read
    # And that the shim still reaches the executable rather than only `open`. This route is
    # the only one that puts `tervin` on PATH, so it is the only one where the documented
    # `tervin daemon start` can work at all — a shim that lost this branch would leave the
    # command on PATH and unable to answer.
    assert_match "Contents/MacOS/tervin", (bin/"tervin").read
    # The manual and the completions, asserted only when the install step emitted them —
    # the same condition the install block runs under, because a tag that predates the
    # words installs neither and `brew test` on it has nothing to assert about them.
    if (man1/"tervin.1").exist?
      assert_match "agent", (man1/"tervin.1").read
      assert_path_exists zsh_completion/"_tervin"
      assert_path_exists bash_completion/"tervin"
      assert_path_exists fish_completion/"tervin.fish"
    end
  end
end
